[tool.poetry]
name = "jackplan"
version = "0.1.0"
description = "Blackjack Simulator Engine"
authors = ["Caesar Kabalan <caesar.kabalan@gmail.com>"]
license = "GPL-3.0+"

[tool.poetry.dependencies]
python = "~3.7"
numpy = "^1.18.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
